# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-04-11 03:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='포스팅 제목을 100자 이내로 써 주세요.', max_length=100)),
                ('content', models.TextField()),
                ('photo', models.ImageField(blank=True, help_text='이미지를 첨부하세요.', upload_to='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
